import type { Metadata } from "next";
import { Suspense } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";

import "./globals.css";
import { Analytics } from "@/lib/posthog";
import { Toaster } from "@/components/ui/sonner";
import { VibizEditorOverlay } from "./_vibiz/EditorOverlay";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "New Vibiz app",
  description: "Generated by the Vibiz CTO.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col">
        <Analytics>
          {/* NuqsAdapter calls useSearchParams() internally. Without the
              Suspense boundary, static prerendering of any client-component
              page (e.g. /login, /signup, /_not-found) hits Next's CSR
              bailout check at build time and the whole build fails.
              Wrapping children once at the root means every page is
              prerender-safe, regardless of how the CTO writes individual
              routes. */}
          <NuqsAdapter>
            <Suspense fallback={null}>{children}</Suspense>
          </NuqsAdapter>
        </Analytics>
        <Toaster />
        <VibizEditorOverlay />
      </body>
    </html>
  );
}
